import React from "react";
import {
  AspectRatio,
  Box,
  Button,
  Center,
  Divider,
  Heading,
  Image,
  SimpleGrid,
  Stack,
  Text,
  VStack,
  Wrap,
  WrapItem,
} from "@chakra-ui/react";

/*IMPORT CUSTOM COMPONENTS*/
import Section from "../components/section";
import Animation from "../components/animation";

/*IMPORT ICONS*/
import { IoMdFilm } from "react-icons/io";
import { IoHeartCircleOutline } from "react-icons/io5";
import { RiArrowRightSFill } from "react-icons/ri";

/*IMPORT DATA FOR DYNAMIC DISPLAYING*/
import contributors from "../datasets/contributors";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zahrada Boží - dokumentární film</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className="header-section" h="100vh">
        <SimpleGrid columns={{ base: 1, lg: 2 }} h="100vh">
          <Box h="100%" overflow="hidden" position="relative">
            <Box className="headings">
              <VStack gap={8}>
                <Image src="/img/logo-cz.png" alt="Zahrada Boží" width="50%" />
                <Heading as="h1" display="none">
                  Zahrada Boží
                </Heading>
                <Heading as="p" color="white">
                  dokumentární film
                </Heading>

                <Stack direction={{ base: "column", xl: "row" }}>
                  <Button
                    size="lg"
                    colorScheme="green"
                    leftIcon={<IoHeartCircleOutline />}
                    rightIcon={<RiArrowRightSFill />}
                  >
                    Podpořte film na HitHitu!
                  </Button>

                  <Link href="#about">
                    <Button
                      size="lg"
                      leftIcon={<IoMdFilm />}
                      rightIcon={<RiArrowRightSFill />}
                    >
                      Chci zjistit více!
                    </Button>
                  </Link>
                </Stack>
              </VStack>
            </Box>
          </Box>
          <Box position="relative">
            <Animation />
          </Box>
        </SimpleGrid>
      </Box>

      <Section anchor="about" heading="O filmu" bg="white">
        <SimpleGrid columns={2}></SimpleGrid>
      </Section>

      <Section
        anchor="trailer"
        heading="Trailer"
        bg="rgba(103,71,11,0.5)"
        color="white"
      >
        <AspectRatio maxW="50vw" ratio={16 / 9} ml="auto" mr="auto">
          <iframe
            title="Zahrada Boží Trailer"
            src="https://www.youtube.com/embed/5LBdLa9f_zI"
            allowFullScreen
          />
        </AspectRatio>
      </Section>

      <Section anchor="donations" heading="Projekt podporují" bg="white">
        <Heading as="h3" size="lg" mt="4rem" mb={6}>
          Generální partner
        </Heading>
        <Center>
          <Link href="">
            <Box px={5} py={10} borderRadius="1rem" w="30rem" bg="green.100">
              <Text textAlign="center">
                Vaše logo, nebo jméno může být tady!
              </Text>
            </Box>
          </Link>
        </Center>

        <Heading as="h3" size="lg" mt="5rem" mb={6}>
          Za podpory
        </Heading>
        <Stack
          my={6}
          direction={{ base: "column", md: "row" }}
          justify="center"
        >
          <Box mx={{ base: 4, md: 12 }}>
            <Image
              className="partner-logo"
              src="/img/Impuls HK black.png"
              alt="Centrum uměleckých aktivit Impuls Hradec Králové"
            />
          </Box>
          <Box mx={{ base: 4, md: 12 }}>
            <Image
              className="partner-logo"
              src="/img/nu.png"
              alt="Northumbria University v Newcastle upon Tyne"
            />
          </Box>
        </Stack>

        <Heading as="h3" size="lg" mt="5rem" mb={6}>
          Skrze HitHit přispěli
        </Heading>

        <Wrap
          className="contributor-wrap"
          align="center"
          spacing={0}
          justify="center"
        >
          {contributors.map((contributor) => (
            <WrapItem h="80px" key={contributor}>
              <Box p={2} w="100%" h="100%" position="relative">
                <Image
                  src="/img/plant.png"
                  alt=""
                  position="absolute"
                  width="50px"
                  height="50px"
                  top="10px"
                  left="-20px"
                  transform={
                    "rotate(" +
                    Math.floor(Math.random() * (20 + 1) - 10) +
                    "deg)"
                  }
                />
                <Center w="100%" h="100%">
                  <Box pl={4} pr={10} py={3} borderRadius="0.5rem">
                    <Text
                      className="contributor"
                      textAlign="center"
                      fontSize="lg"
                      fontWeight="600"
                    >
                      {contributor}
                    </Text>
                  </Box>
                </Center>
              </Box>
            </WrapItem>
          ))}

          <WrapItem h="80px">
            <Box p={5} w="100%" h="100%" position="relative">
              <Image
                src="/img/sad-little-cup.png"
                alt=""
                position="absolute"
                width="50px"
                height="50px"
                top="10px"
                left="-30px"
                transform={
                  "rotate(" + Math.floor(Math.random() * (20 + 1) - 10) + "deg)"
                }
              />
              <Center w="100%" h="100%">
                <Link href="">
                  <Box px={5} py={3} borderRadius="0.5rem" bg="green.100">
                    <Text
                      className="contributor"
                      textAlign="center"
                      fontSize="lg"
                    >
                      Vaše jméno může být tady!
                    </Text>
                  </Box>
                </Link>
              </Center>
            </Box>
          </WrapItem>
        </Wrap>
      </Section>

      <Section anchor="contacts" heading="Kontakty"></Section>

      <Section anchor="press" heading="Ke stažení"></Section>
    </>
  );
}
