import React from "react";
import Head from "next/head";
import Link from "next/link";
import {
  AspectRatio,
  Box,
  Button,
  Card,
  CardBody,
  CardFooter,
  Center,
  Heading,
  Image,
  SimpleGrid,
  Stack,
  Text,
  VStack,
  Wrap,
  WrapItem,
} from "@chakra-ui/react";

/*IMPORT CUSTOM COMPONENTS*/
import Section from "../components/section";
import Animation from "../components/animation";

/*IMPORT ICONS*/
import { IoMdFilm } from "react-icons/io";
import { IoHeartCircleOutline } from "react-icons/io5";
import { RiArrowRightSFill } from "react-icons/ri";
import { BiChevronDown } from "react-icons/bi";

/*IMPORT DATA FOR DYNAMIC DISPLAYING*/
import contributors from "../datasets/contributors";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zahrada Boží - dokumentární film</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className="header-section" h="100vh">
        <SimpleGrid columns={{ base: 1, lg: 2 }} h="100vh">
          <Box h="100%" overflow="hidden" position="relative">
            <Box className="headings">
              <VStack gap={8}>
                <Image src="/img/logo-cz.png" alt="Zahrada Boží" width="50%" />
                <Heading as="h1" display="none">
                  Zahrada Boží
                </Heading>
                <Heading as="p" color="white">
                  dokumentární film
                </Heading>

                <Stack direction={{ base: "column", xl: "row" }}>
                  <Button
                    size="lg"
                    colorScheme="green"
                    leftIcon={<IoHeartCircleOutline />}
                    rightIcon={<RiArrowRightSFill />}
                  >
                    Podpořte film na HitHitu!
                  </Button>

                  <Link href="#about">
                    <Button
                      size="lg"
                      leftIcon={<IoMdFilm />}
                      rightIcon={<RiArrowRightSFill />}
                    >
                      Chci zjistit více!
                    </Button>
                  </Link>
                </Stack>
              </VStack>
            </Box>
          </Box>
          <Box position="relative">
            <Animation />
          </Box>
        </SimpleGrid>
      </Box>

      <Section anchor="about" heading="O filmu" bg="white">
        <SimpleGrid columns={2}>
          <Box>
            <Text>
              &quot;To bylo už dávno. To jsem byl ještě mladý a krásný. Teď už
              jsem jenom krásný...&quot;
            </Text>
            <Text>- Imrich Špitálský</Text>
            <Heading as="h3">Treatment</Heading>
            <Text>
              Dokumentární snímek zachycující intimní portrét muže smiřujícího
              se se svým věkem a ztrátou celoživotního díla. Prožívající podzim
              svého života pečuje o svou zahradu, vtipkuje se svou ženou a
              vzpomíná na celoživotní cestu plnou lásky k přírodě, radosti,
              strastí a cibulí.
            </Text>
            <Heading as="h3">Synopse</Heading>
            <Text>
              Před padesáti lety si pronajal Imrich pozemek na okraji Ústí nad
              Orlicí v zahrádkářské osadě. V té době ovšem pozemek nebyl ničím
              než kopřivami zarostlou bažinou. Pocházeje z jižního Slovenska,
              kde půda znamenala vše, Imrich věnoval většinu svého života
              zkultivování své zahrady, která se stala jeho láskou a náplní
              volného času.
            </Text>
            <Text>
              Od jara do zimy, rok za rokem se o ni staral a vedl zahrádkářský
              výbor. Mezitím přišly děti, vnoučata a změna režimu. Po revoluci
              se však pozemek stal předmětem církevních restitucí a veškerá
              snaha o jeho odkoupení narazila na nepřátelský odpor. Imrich byl
              tímto rozhodnutím zdrcen, ale dodnes nadále aktivně pečuje o
              zahrádku.
            </Text>
            <Text>
              Ve svém boji musí čelit stáří, počasí, škůdcům, vlastníkům půdy a
              zhoršujícímu se zdravotnímu stavu. Existuje šance, že se Imrich
              „na stará kolena“ vzdá zahrady a prodá ji, nebo se mu stane tento
              kus země osudným?
            </Text>
            <Text>
              Dokumentární film nabízí intimní portrét stárnoucího člověka s
              láskou k přírodě, který se smiřiuje se svým věkem a ztrátou
              celoživotního díla. Mezitím vzpomíná s humorem na své mládí,
              vtipkuje se svou ženou a pyšní se z každého výsledku a malého
              vítězství, které mu půda a život dopřeje.
            </Text>
          </Box>
          <Box>
            <Heading as="h3">Tým</Heading>
            <Heading as="h4">Michal Špitálský</Heading>
            <Heading as="h4">Jakub Tesařík</Heading>
            <Heading as="h4">Sam Enticknap</Heading>
          </Box>
        </SimpleGrid>
      </Section>

      <Section
        anchor="trailer"
        heading="Trailer"
        bg="rgba(103,71,11,0.5)"
        color="white"
      >
        <AspectRatio maxW="50vw" ratio={16 / 9} ml="auto" mr="auto">
          <iframe
            title="Zahrada Boží Trailer"
            src="https://www.youtube.com/embed/5LBdLa9f_zI"
            allowFullScreen
          />
        </AspectRatio>
      </Section>

      <Section anchor="donations" heading="Projekt podporují" bg="white">
        <Heading as="h3" size="lg" mt="4rem" mb={6}>
          Generální partner
        </Heading>
        <Center>
          <Link href="">
            <Box
              px={5}
              py={10}
              borderRadius="1rem"
              w={{ base: "100%", md: "100%" }}
              bg="green.100"
            >
              <Text textAlign="center">
                Vaše logo, nebo jméno může být tady!
              </Text>
            </Box>
          </Link>
        </Center>

        <Heading as="h3" size="lg" mt="5rem" mb={6}>
          Za podpory
        </Heading>
        <Stack
          my={6}
          direction={{ base: "column", md: "row" }}
          spacing={12}
          justify="center"
        >
          <Box mx={{ base: 4, md: 12 }}>
            <Image
              className="partner-logo"
              src="/img/Impuls HK black.png"
              alt="Centrum uměleckých aktivit Impuls Hradec Králové"
              mx="auto"
            />
          </Box>
          <Box mx={{ base: 4, md: 12 }}>
            <Image
              className="partner-logo"
              src="/img/nu.png"
              alt="Northumbria University v Newcastle upon Tyne"
              mx="auto"
            />
          </Box>
        </Stack>

        <Heading as="h3" size="lg" mt="5rem" mb={6}>
          Skrze HitHit přispěli
        </Heading>

        <Wrap
          className="contributor-wrap"
          align="center"
          spacing={0}
          justify="center"
        >
          {contributors.map((contributor) => (
            <WrapItem
              h="80px"
              key={contributor}
              w={{ base: "90%", sm: "50%", md: "unset" }}
              pl={{ base: 8, md: 0 }}
            >
              <Box p={2} w="100%" h="100%" position="relative">
                <Image
                  src="/img/plant.png"
                  alt=""
                  position="absolute"
                  width="50px"
                  height="50px"
                  top="10px"
                  left="-20px"
                  transform={
                    "rotate(" +
                    Math.floor(Math.random() * (20 + 1) - 10) +
                    "deg)"
                  }
                />
                <Center w="100%" h="100%">
                  <Box pl={4} pr={10} py={3} borderRadius="md">
                    <Text
                      className="contributor"
                      textAlign="center"
                      fontSize="lg"
                      fontWeight="600"
                    >
                      {contributor}
                    </Text>
                  </Box>
                </Center>
              </Box>
            </WrapItem>
          ))}

          <WrapItem h="80px">
            <Box p={5} w="100%" h="100%" position="relative">
              <Image
                src="/img/sad-little-cup.png"
                alt=""
                position="absolute"
                width="50px"
                height="50px"
                top="10px"
                left="-30px"
                transform={
                  "rotate(" + Math.floor(Math.random() * (20 + 1) - 10) + "deg)"
                }
              />
              <Center w="100%" h="100%">
                <Link href="">
                  <Box px={5} py={3} borderRadius="md" bg="green.100">
                    <Text
                      className="contributor"
                      textAlign="center"
                      fontSize="lg"
                    >
                      Vaše jméno může být tady!
                    </Text>
                  </Box>
                </Link>
              </Center>
            </Box>
          </WrapItem>
        </Wrap>
      </Section>

      <Section anchor="contacts" heading="Kontakty"></Section>

      <Section anchor="press" heading="Ke stažení" bg="white">
        <Wrap
          align="center"
          spacing={8}
          justify="center"
          py={5}
          className="downloads-wrap"
        >
          {/* KARTA PRO STÁHNUTÍ LOGA */}
          <WrapItem>
            <Card maxW="sm">
              <CardBody>
                <Image
                  src="/img/Impuls HK black.png"
                  borderRadius="lg"
                  alt=""
                />
                <Stack mt="6" spacing="3">
                  <Heading as="h3" size="md">
                    Logotyp
                  </Heading>
                  <Text>
                    This sofa is perfect for modern tropical spaces, baroque
                    inspired spaces, earthy toned spaces and for people who love
                    a chic design with a sprinkle of vintage design.
                  </Text>
                </Stack>
              </CardBody>
              <CardFooter>
                <Button colorScheme="green" rightIcon={<BiChevronDown />}>
                  Stáhnout (.zip)
                </Button>
              </CardFooter>
            </Card>
          </WrapItem>

          {/* KARTA PRO STÁHNUTÍ PLAKÁTŮ */}
          <WrapItem>
            <Card maxW="sm">
              <CardBody>
                <Image
                  src="/img/Impuls HK black.png"
                  borderRadius="lg"
                  alt=""
                />
                <Stack mt="6" spacing="3">
                  <Heading as="h3" size="md">
                    Plakáty
                  </Heading>
                  <Text>
                    This sofa is perfect for modern tropical spaces, baroque
                    inspired spaces, earthy toned spaces and for people who love
                    a chic design with a sprinkle of vintage design.
                  </Text>
                </Stack>
              </CardBody>
              <CardFooter>
                <Button colorScheme="green" rightIcon={<BiChevronDown />}>
                  Stáhnout (.zip)
                </Button>
              </CardFooter>
            </Card>
          </WrapItem>

          {/* KARTA PRO STÁHNUTÍ PRESS-KITU */}
          <WrapItem>
            <Card maxW="sm">
              <CardBody>
                <Image
                  src="/img/Impuls HK black.png"
                  borderRadius="lg"
                  alt=""
                />
                <Stack mt="6" spacing="3">
                  <Heading as="h3" size="md">
                    Press-kit
                  </Heading>
                  <Text>
                    This sofa is perfect for modern tropical spaces, baroque
                    inspired spaces, earthy toned spaces and for people who love
                    a chic design with a sprinkle of vintage design.
                  </Text>
                </Stack>
              </CardBody>
              <CardFooter>
                <Button colorScheme="green" rightIcon={<BiChevronDown />}>
                  Stáhnout (.zip)
                </Button>
              </CardFooter>
            </Card>
          </WrapItem>
        </Wrap>
      </Section>
    </>
  );
}
